server:
  port: 8081
  url: localhost
  pageUrl: http://localhost:8081/forum_crawler

jdbc:
  dbhost: localhost
  slave: localhost
  dbname: forum_crawler
  username: root
  password: root
  maxPoolSize: 3

spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
