@urlBase=http://localhost:8081

POST {{urlBase}}/api/v1/threads/crawl
Content-Type: application/json

{
    "url": "https://voz.vn/t/intel-cong-bo-vi-xu-ly-intel-core-the-he-14.904923/",
    "source": "voz"
}
