@urlBase=http://localhost:8081/ai-summarizer

@sourceTypeStr=voz
@url=https://voz.vn/t/chon-nikon-z5-hay-sony-a7r2.889618/
###
GET {{urlBase}}/api/v1/crawler/{{sourceTypeStr}}?url={{url}}
Content-Type: application/json


