@urlBase=http://localhost:8081

@url=https://voz.vn/t/intel-cong-bo-vi-xu-ly-intel-core-the-he-14.904923/

// get thread
GET {{urlBase}}/api/v1/threads?url={{url}}
Content-Type: application/json

### get summary
POST  {{urlBase}}/api/v1/threads/summary?url={{url}}
Content-Type: application/json

